# Site settings
title: Zetsu
email: zetsu@domain.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/zetsu"
url: "http://yourdomain.com"

author:
  name     : 'Fernando Moreira'
  email    : hi@nandomoreira.me
  url      : http://nandomoreira.me

github: https://github.com/nandomoreirame/zetsu

# Build settings
markdown: kramdown
